### ISSUE TITLE
MOD Conflict : Blur with TacZ's guns modifying panel

### ISSUE THREAD

**Issue by p0rt39** [Motschen/Blur#102]
### General
When **TacZ{A gun mod)** and **Blur** are loaded together,Blur will wrongly add a blur filter onto TacZ's guns modifying panel.
It doesn't cause a crash of funcion failure,Though,but the visual effect error is annoying.
I'm not a native English speaker,so there may be some inapproprite expressions in my words.**I apologize in advance.**
PS.There is also a issue on TacZ's Github page(links below).

---

#### Minecraft
Minecraft version : 1.20.1
Forge Version : 47.2.23
#### TacZ
TacZ Version : [snapshot-2024060613151717679706](https://github.com/MCModderAnchor/TACZ/releases/tag/snapshot-2024060613151717679706)
The Issue : https://github.com/MCModderAnchor/TACZ/issues/25 (In Simplified Chinese)
GitHub Page : https://github.com/MCModderAnchor/TACZ
#### Blur
Blur Version : https://www.curseforge.com/minecraft/mc-mods/blur (The newest release version on CurseForge page)

---

### BUG Screenshot
![image](https://github.com/MCModderAnchor/TACZ/assets/122146865/69ab576c-3361-4437-8f46-b173120c70a8)

**Comment by TartaricAcid** [comment]
1. First, Blur is a Fabric mod, and you are using the ReBlured mod.
    Reblured Mod Github: <https://github.com/Cheaterpaul/ReBlured>

2. ReBlured mod provides a configuration file that can turn off the background blur of certain screen.
    You can modify the configuration file as follows:
   ```toml
   #A list of classes to be excluded from the blur shader.
   guiExclusions = [
       "net.minecraft.client.gui.screens.ChatScreen", 
       "net.minecraft.client.gui.screens.InBedChatScreen", 
       "com.tacz.guns.client.gui.GunRefitScreen"
   ]
   ```

**Comment by p0rt39** [comment]
> 1. First, Blur is a Fabric mod, and you are using the ReBlured mod.首先，模糊是一个织物mod，你使用的是rebirited mod。
>    Reblured Mod Github: https://github.com/Cheaterpaul/ReBluredReblred Mod Github: https://github.com/Cheaterpaul/ReBlured
> 2. ReBlured mod provides a configuration file that can turn off the background blur of certain screen.Reblred mod提供了一个配置文件，可以关闭某些屏幕的背景模糊。
>    You can modify the configuration file as follows:您可以修改配置文件，如下所示:
>    ```toml
>    #A list of classes to be excluded from the blur shader.
>    guiExclusions = [
>        "net.minecraft.client.gui.screens.ChatScreen", 
>        "net.minecraft.client.gui.screens.InBedChatScreen", 
>        "com.tacz.guns.client.gui.GunRefitScreen"
>    ]
>    ```

Actually the mod is Blur(Forge) https://www.curseforge.com/minecraft/mc-mods/blur-forge
I've mistaken these mods which have similar function.
Despite this,this method DOES fix the problem.
I sincerely apologize for the inconvience and mistakes I caused due to my lack of knowledge.
