### ISSUE TITLE
GUI Exclusions not configurable

### ISSUE THREAD

**Issue by Big-Iron-Cheems** [Motschen/Blur#11]
> guiExclusions
> A list of classes to be excluded from the blur shader. This is to be used for GUIs which do not necessarily cover the screen. It defaults to containing only one GUI, the chat.

The mod page talks about the ability to choose when to blur the screen by filtering GUIs, but there is no such option in the config screen. Am I missing something or is this feature still WIP?
![2021-03-28 18_20_30-Minecraft_ 1 16 5](https://user-images.githubusercontent.com/52252627/112759216-54a6b080-8ff2-11eb-9876-224c64e0cf74.png)

**Comment by Motschen** [comment]
It can only be configured in the file due to limitations of the config api. Ingame support for that is planned however.
The file can be found at ~/.minecraft/config/blur.json

**Comment by Motschen** [comment]
Fixed in the latest version :)
