### ISSUE TITLE
Blur+ does not work on 1.20.1

### ISSUE THREAD

**Issue by airon-main** [Motschen/Blur#112]
blur+ 3.1.0
mc 1.20.1
![image](https://github.com/user-attachments/assets/4070eb48-0b65-4922-b79d-f2755c4612b4)

expected
blur+ 4.0.0
mc 1.20.6
![image](https://github.com/user-attachments/assets/3af87610-5b29-46db-8621-631c12c1f607)

**Comment by Motschen** [comment]
Blur+ is only available for 1.21.4 onwards, as this version introduced blur in vanilla, and Blur+ is meant to improve the vanilla blur effect.
