### ISSUE TITLE
issue with fabric + optifine + blur doesn't work

### ISSUE THREAD

**Issue by nottabandaid** [Motschen/Blur#13]
![2021-04-25_02 46 57](https://user-images.githubusercontent.com/20377250/115988956-b5cd8f80-a570-11eb-8469-dcd1172deac3.png)
If you are using optifine with fabric and the blur plug in shaders do not work because of the satin api.

**Comment by Motschen** [comment]
Not much I can do about that, but with the recent changes related to shaders in 1.17 snapshots, Satin will probably no longer be needed.
