### ISSUE TITLE
Blur exclusions not defaulting to excluding chat with OptiFine installed

### ISSUE THREAD

**Issue by tort-oise** [Motschen/Blur#16]
I'm pretty sure this is a bug. Fresh install, Fabric, I have done absolutely nothing to the config, and it still blurs the chat bar. In the CurseForge page, it says it defaults to excluding the chat window, but that is clearly not what it does. 

I can provide further screenshots of my .json config files, and my screen still blurring. I have no idea how to code properly so I have no idea how to manually insert it, either.

**Comment by ghost** [comment]
I'm having the exact same issue: fresh install, chat blurred by default and don't know how to exclude the chat myself.

**Comment by tort-oise** [comment]
To comment on this, it seems OptiFabric is the problem. Switching to newly-released Sodium made it run fine, but I think you should still look into it.

**Comment by Motschen** [comment]
I think this happens because OptiFine makes the chat use a completely new class for some really weird reason.
But that's only a guess, as I can't look at OptiFine's code, since it's not open-source.
I'll try to come up with a solution in the next update.

**Comment by tort-oise** [comment]
You don't think you could ask in the Optifine Discord or Reddit or something?

**Comment by Motschen** [comment]
Please turn on the option "Show screen name" in the latest release and tell me the name it shows for the OptiFine chat screen. For some reason, I can't even start OptiFine with Blur installed.

**Comment by tort-oise** [comment]
Using the latest Optifine/Optifabric versions gives me the error message
`[16:59:56] [Render thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper':`
before crashing.

I'm gonna look into using older Optifine versions, because I have a clear memory of them working together.

**Comment by tort-oise** [comment]
I got it to boot! I used an Optifine version from one of my old MultiMC instances that isn't listed on the Optifine website (`preview_OptiFine_1.17.1_HD_U_G9_pre30.jar`). 
Something in the final release is preventing OptiFine to boot with Blur. But, then again, we have no way of knowing that, seeing as Optifine isn't open-source. Sigh. 

Anyways, I found the screen name in this version; "net.optifine.gui.GuiChatOF". 
![image](https://user-images.githubusercontent.com/81963124/140975448-cbc0b7ed-6b92-4ea8-b8d8-a5da209334e8.png)
Excluding this in the settings makes it not blur anymore.
![image](https://user-images.githubusercontent.com/81963124/140975675-67e961a3-7050-483d-a04c-80a14e498e2a.png)

I don't think they've changed that in the newer version. Odd that they change the name of the chat window, too. It feels useless. I can also see the screen names of the Optifine settings windows, and they blur, and work fine. 
However, there's still the issue of newer Optifine versions not working with Blur for some reason. You keep talking about how all the library mods you use are so incompatible, why not find alternatives?

**Comment by Motschen** [comment]
Thanks for figuring out how to get it working.
The problem is with the library called Satin, it allows mod devs (like me) to easily make use of shader effects in their mods.
As far as I'm aware, there's no alternative to Satin and even if I got it working without Satin, OptiFine would have problems, because it's just not designed for modded gameplay.

**Comment by tort-oise** [comment]
Well, a current fix is adding the Optifine chat window to the default exclusions. 
Optifine's kinda shit, but that isn't the focus here, and a fix has already been found, mind if I close it?
