### ISSUE TITLE
1.17 version of Blur is not pushed to Modrinth

### ISSUE THREAD

**Issue by fyyrraaa** [Motschen/Blur#18]
I noticed that Blur is released for 1.17.x in GitHub but not in Modrinth. I wonder if that's intentional or not, nor if this is the proper place to report it.

**Comment by tort-oise** [comment]
This issue page is basically dead, but to give you a reply: they probably forgot about Modrinth. It's released on CurseForge though.

**Comment by Motschen** [comment]
Blur 2.3.0 is now on Modrinth, sorry for the delay, I wasn't able to login to Modrinth for a while.
