### ISSUE TITLE
Exception while loading entries for client entrypoint

### ISSUE THREAD

**Issue by RyanCR03** [Motschen/Blur#2]
The game crashed whilst initializing game
Error: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'client' provided by 'blur'
Exit Code: -1

https://pastelink.net/28i9p

**Comment by Motschen** [comment]
Seems like Satin wasn't loaded correctly, maybe a conflict with optifine, since optifine and satin never worked that well together.

**Comment by thesamgordon** [comment]
I'm also having this issue. I have no other mods. Using the latest version on Fabric and Blur. Any ideas?

https://pastebin.com/X5KzJFBx

**Comment by RyanCR03** [comment]
I found a mod that fixes this https://www.curseforge.com/minecraft/mc-mods/fabric-zero
