### ISSUE TITLE
Incorrectly labeled manifests: JAR's keep being marked as 2.1.0

### ISSUE THREAD

**Issue by PanoptesDreams** [Motschen/Blur#26]
Can you please make sure to update your manifests so that this stops happening.
It makes version tracking and updating tiresome

2.1.0 (snapshot), 2.2.0, 2.2.1 & 2.3.0 for 1.17 are all affected

For reference
![image](https://user-images.githubusercontent.com/55162814/136113687-f1573e17-c70a-4e80-8ae9-02ef0d0ff8f9.png)
![image](https://user-images.githubusercontent.com/55162814/136113707-24f6c81a-eb60-48c5-a1bb-97adf7a87625.png)

**Comment by Motschen** [comment]
Fixed in the latest version, sorry for any inconveniences.
