### ISSUE TITLE
[Suggestion] make blur exclusion capable of wildcards or packages

### ISSUE THREAD

**Issue by yuri0r** [Motschen/Blur#38]
Basicly the title. If I wanted to exclude all of iris and sodium GUI's from blur it would be great to use

```
 "net.coderbot.iris.gui.*",
 "me.jellysquid.mods.sodium.client.gui.*"
```
 
 in the config instead of adding all the classes by hand
 
 probably also helpful for modpacks when GUI's from certain mods don't play ball nicely with blur.

**Comment by Motschen** [comment]
I added this feature back in Juli, just without the asterisks.
