### ISSUE TITLE
[Bug] Uppon installation my game crashes and I get the following error:

### ISSUE THREAD

**Issue by RaptaG** [Motschen/Blur#39]
---- Minecraft Crash Report ----
// You're mean.

Time: 2/6/22, 11:28 AM
Description: Initializing game

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/class_5944.<init>(Lnet/minecraft/class_5912;Ljava/lang/String;Lnet/minecraft/class_293;)V @7: invokespecial
  Reason:
    Type uninitializedThis (current frame, stack[2]) is not assignable to 'net/minecraft/class_5944'
  Current Frame:
    bci: @7
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'net/minecraft/class_5912', 'java/lang/String', 'net/minecraft/class_293' }
    stack: { uninitializedThis, 'net/minecraft/class_5912', uninitializedThis, 'java/lang/String', 'net/minecraft/class_5912', 'java/lang/String', 'net/minecraft/class_293' }
  Bytecode:
    0000000: 2a2b 2a2c 2b2c 2db7 005c 59c7 000d bb00
    0000010: 5e59 1260 b700 63bf 2db7 0066 b1       
  Stackmap Table:
    full_frame(@24,{UninitializedThis,Object[#109],Object[#111],Object[#113]},{UninitializedThis,Object[#109],Object[#115]})

	at net.minecraft.class_757.method_34521(class_757.java:439)
	at net.minecraft.class_310.<init>(class_310.java:617)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_34521(class_757.java:439)
	at net.minecraft.class_310.<init>(class_310.java:617)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.16.5-zen1-1-zen
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1132666288 bytes (1080 MiB) / 1577058304 bytes (1504 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 PRO 4750G with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Renoir
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x1636
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 23046.41
	Virtual memory used (MB): 6686.27
	Swap memory total (MB): 15364.00
	Swap memory used (MB): 3.75
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.3
		architectury: Architectury 3.6.15
		armorchroma: Armor Chroma 1.2.0
		autoswitch: AutoSwitch 3.5.0
		autoswitch-api: AutoSwitch API 1.0.0
		bendy-lib: Bendy api 2.0.4
		betterdroppeditems: Better Dropped Items 1.3.1-21w37a
		blur: Blur (Fabric) 2.4.1
		chat-up: Chat Up! 2.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		controlling: Controlling For Fabric 9.0+13
		custom-crosshair-mod: Custom Crosshair Mod 1.3.8-fabric
		dsurround: §6Dynamic Surroundings§r: §eFabric Edition 0.0.4
		easiervillagertrading: EasierVillagerTrading 1.18-fabric0.43.1-1.5.4
		easymagic: Easy Magic 3.2.1
		emotecraft: Emotecraft 2.1-SNAPSHOT-build.9
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.46.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.10+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.13+b0b66fc365
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+13eda06565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.0+0a73a6c265
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		forgeconfigapiport: Forge Config API Port 3.1.1
		fpsdisplay: FPS-Display 1.4.2+1.18
		freelook: freelook 1.1.1
		gbfabrictools: GBfabrictools 1.3.4+1.18
		iceberg: Iceberg 1.0.38
		inventoryhud: Inventory HUD + 3.4.2
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0-beta.2
		libzoomer: LibZoomer 0.3.0+1.17.1
		malilib: MaLiLib 0.11.5
		me_hypherionmc_simple-rpc-common: simple-rpc-common 1.0.17
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		minecraftcapes: MinecraftCapes Mod 12.0.2
		minihud: MiniHUD 0.21.3
		minimalmenu: MinimalMenu 1.18.1-0.1.4
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		notenoughanimations: NotEnoughAnimations 1.4.0
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		optifabric: OptiFabric 1.12.10
		org_aeonbits_owner_owner: owner 1.0.12
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		paperdoll: PaperDoll 1.0.0-mc1.18-pre1
		presencefootsteps: Presence Footsteps 1.4.0
		puzzleslib: Puzzles Lib 3.1.3
		replanter: Replanter 1.3
		replaymod: Replay Mod 1.18.1-2.6.3
		satin: Satin 1.7.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		signtools: Sign Tools 1.0.0
		simple-rpc: Simple Rpc 2.7.1
		skinlayers: 3d Skin Layers 1.3.1
		smoothswapping: Smooth Swapping 0.4.4
		spruceui: SpruceUI 3.3.0+1.17
		visualworkbench: Visual Workbench 3.1.0
		waveycapes: WaveyCapes 1.0.4
		worldedit: WorldEdit 7.2.9+e20e013
		xaerominimap: Xaero's Minimap 22.1.1
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD RENOIR (DRM 3.44.0, 5.16.5-zen1-1-zen, LLVM 13.0.0) GL version 4.6 (Core Profile) Mesa 21.3.5, AMD
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 16x AMD Ryzen 7 PRO 4750G with Radeon Graphics
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6 (Core Profile) Mesa 21.3.5
	OpenGlRenderer: AMD RENOIR (DRM 3.44.0, 5.16.5-zen1-1-zen, LLVM 13.0.0)
	OpenGlVendor: AMD
	CpuCount: 16

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18.1
	OptiFine jar version: OptiFine_1.18.1_HD_U_H4
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: /mnt/Storage/Others/Games/Minecraft/Java/1.18 Fabric/.optifine/OptiFine_1.18.1_HD_U_H4/Optifine-mapped.jar
	OptiFabric error: <None>

Also here is what I  get from the launcher:
![Screenshot](https://user-images.githubusercontent.com/77157639/152674913-123b0c73-491a-48ef-a6b7-38f8d48404f5.png)

**Comment by invisyarcticfox** [comment]
yeah im getting the same error in the launcher too

**Comment by Motschen** [comment]
Caused by OptiFine, which is now no longer supported at all, sorry :(
