### ISSUE TITLE
Add any kind of graphical setting screen to the default list of excluded GUIs

### ISSUE THREAD

**Issue by twome** [Motschen/Blur#44]
These UIs can benefit massively from having a transparent background, so users can see graphical changes live as they tinker, without having to menu-dive between each edit. In particular, Iris (or maybe it's Sodium?) has transparent backgrounds for the graphics and shader settings UI pages - I imagine that'd include a large proportion of Blur users. As a lay-user I'm not sure how to go about finding the names of Minecraft's UI panels (especially mods' panels) - that might be a useful link for Blur's readme, too. Love the mod, it works absolutely gorgeously on the vanilla UIs!

**Comment by Motschen** [comment]
There's a config option that enables the display of the current screen's path.
I'm also working on wildcards to allow the easy disabling for screens of the same mod, I'll finish it when I have time.

**Comment by twome** [comment]
Ah, thanks!

**Comment by Motschen** [comment]
This was added in 2.5.0, so I'll close this issue.
