### ISSUE TITLE
[Compatibility] Abnormally high rendering load from the "weather" source with Figura

### ISSUE THREAD

**Issue by Felix14-v2** [Motschen/Blur#46]
When using Blur together with Figura, FPS drops significantly, and the debug pie shows an increased load from the "weather" source.

<details>
 <summary>Demo</summary>

**Figura only**
![image](https://user-images.githubusercontent.com/75726196/173636654-29e584b4-6c01-4af2-852d-0c2c452e0495.png)

**Figura & Blur**
![image](https://user-images.githubusercontent.com/75726196/173636372-9d46c01f-81bf-473a-ad17-b094c57404d5.png)
![image](https://user-images.githubusercontent.com/75726196/173632484-5f882990-70ac-4d47-b939-27e854445bba.png)
</details>

[latest.log](https://github.com/Motschen/Blur/files/8902029/latest.log)
[crash-2022-06-14_20.17.48-client.txt](https://github.com/Motschen/Blur/files/8902027/crash-2022-06-14_20.17.48-client.txt)

**Info**
- Minecraft: 1.19
- Fabric Loader: 0.14.7
- Fabric API: 0.55.3
- OS: Windows 10
- Java: Eclipse Adoptium jdk-17.0.1.12-hotspot

**Additional**
[Figura#196](https://github.com/Moonlight-MC/Figura/issues/196)

**Comment by aaKugelblitz** [comment]
I'm getting the same issue with my usual mod loadout, however testing showed I'm also getting this problem without the use of any other mods (beside cloth config and fabric api). This gets me the same high rendering load from weather and subsequent FPS drop. 

Version 1.19.1
Fabric loader 0.14.8
Fabric api 0.58.5
MacOS 12.4 (I know, I know)
pretty sure I'm also on java 17 but id have to go check

**Comment by Motschen** [comment]
Seems to be the same as #21, so I'll close this one.
