### ISSUE TITLE
Changing resource packs causes the blur to go away no matter how high you set Blend Radius

### ISSUE THREAD

**Issue by CalXee** [Motschen/Blur#5]
Changing packs causes that feature to not work at all.

**Comment by Motschen** [comment]
After I've changed resourcepacks I just need to go back into the game and open the pause screen again. and it works just fine.

**Comment by LatvianModder** [comment]
Just reloading resources with F3+T in general also has same effect

**Comment by Motschen** [comment]
Does this issue still occur on the latest Blur for 1.17?
