### ISSUE TITLE
Blur Radius always resets to 8 when re-opening client with this mod, no matter what other value you set it to.

### ISSUE THREAD

**Issue by CalXee** [Motschen/Blur#6]
No matter what value you have set, upon re-opening the client the blur radius is always the default 8. Even if the modmenu UI shows it's not 8, it is.

**Comment by Motschen** [comment]
Cannot reproduce on my end, could you provide more information? Which minecraft version are you using? Are you using any other mods?

**Comment by CalXee** [comment]
https://youtu.be/rpDfwvzSfTs is the video showcasing the issue. No other mods installed.

**Comment by YoshiAye** [comment]
Same issue here. Version is 1.16.5

**Comment by Motschen** [comment]
Could you try if it also happens on 2.1.0?

**Comment by Justsnoopy30** [comment]
It does, just confirmed.

**Comment by Justsnoopy30** [comment]
Well actually it happens 100% of the time when blur radius is set to 0, and sometimes when it is set to 1 or above.

**Comment by Motschen** [comment]
Doesn't seem to occur in the latest version anymore, can you confirm?

**Comment by Motschen** [comment]
Gonna close this now, since it seems to be fixed.
