### ISSUE TITLE
Crashing in 1.19.3

### ISSUE THREAD

**Issue by TheButterbrotMan** [Motschen/Blur#60]
Hello, sadly this mod crashes with new 1.19.3 release.

https://bytebin.lucko.me/wf5mBojb6e

**Comment by backryun** [comment]
Of course, because this mod not ready for 1.19.3
This mod has dependency "midnightlib", but midnightlib not ready for 1.19.3
This is why you can not run yet this mod on 1.19.3
Just wait a momment. I managing this mod, When midnightlib start support 1.19.3 I`ll do now update this mod too.

+midnightlib start support 1.19.3 but it is not 100%. i`m trying to use new version on this mod.

**Comment by Motschen** [comment]
MidnightLib 1.1.0 with full 1.19.3 support has been out since about a week ago, I've just pretty busy with school, but I'll try to port as many of my mods as possible this weekend.

**Comment by backryun** [comment]
Oh I saw the midnightlib is configured on 1.19.3-rc1, so we need to wait until official fabric API about 1.19.3 release.
Isn't it right?

**Comment by TheButterbrotMan** [comment]
> Oh I saw the midnightlib is configured on 1.19.3-rc1, so we need to wait until official fabric API about 1.19.3 release. Isn't it right?

https://www.curseforge.com/minecraft/mc-mods/midnightlib/files/4159149

**Comment by Motschen** [comment]
It doesn't matter that it's configured for 1.19.3-rc1, it'll work just fine anyway.

**Comment by tad-dufort** [comment]
it appears to have an outdated version of satin aswell

**Comment by backryun** [comment]
> Hello, sadly this mod crashes with new 1.19.3 release.
> 
> https://bytebin.lucko.me/wf5mBojb6e

https://github.com/backryun/Blur/actions/runs/3676229704
Please test this build, I fix all can works on 1.19.3!

**Comment by InQuognito** [comment]
The crash for me is caused by missing a dependency named Satin, which isn't out for 1.19.3.

**Comment by TheButterbrotMan** [comment]
I think it is https://github.com/Ladysnake/Satin/releases
