### ISSUE TITLE
Make it obvious that Blur requires Satin

### ISSUE THREAD

**Issue by colby-boucher** [Motschen/Blur#66]
Modrinth doesn't include a Dependencies page like CurseForge, and nowhere in Blur's description does it explicitly state that Satin is required, unless you happen to notice that it "doesn't work with Optifine shaders due to an issue with Satin". Just putting a message right at the top of the description that Satin or Canvas are hard requirements would save a lot of useless issue reports.

**Comment by Motschen** [comment]
Well, Satin is already included with the mod, so stating it being a requirement would just confuse users.
