### ISSUE TITLE
Crash in 1.19.4

### ISSUE THREAD

**Issue by HhiPyrene** [Motschen/Blur#67]
[crash-2023-03-26_24.09.52.8194-quilt_loader.txt](https://github.com/Motschen/Blur/files/11069371/crash-2023-03-26_24.09.52.8194-quilt_loader.txt)
[latest.log](https://github.com/Motschen/Blur/files/11069372/latest.log)
Used the latest build.

**Comment by Motschen** [comment]
I just published Blur 3.0.0, which works for 1.19.4
