### ISSUE TITLE
Blur activated when opening the chat

### ISSUE THREAD

**Issue by ungive** [Motschen/Blur#7]
## Expected Behaviour
I can see my surroundings when I type in the chat or just have it opened.

## Actual Behaviour
When I open the chat (with `T`) the environment blurs.

## Reasoning
I want to see my surroundings for several reasons.

1. When I don't want the game to capture my mouse I open the chat. I still want to see everything.
2. When I'm chatting with someone standing in front of me I don't want their face to melt away. :)
3. When I'm typing during the heat of a battle I'd like to be able to capture movement of opponents.

Currently your mod is not usable for me because of these reasons, even though I really love the aesthetics it adds to the game.

Thanks for reading.

**Comment by Motschen** [comment]
Could you try it with the latest version?

**Comment by ungive** [comment]
Works! :)
