### ISSUE TITLE
Can't input letters into gradient boxes in 1.18.2 on Fabric

### ISSUE THREAD

**Issue by mothcollector** [Motschen/Blur#78]
For example, if I try to write 5500FF, which is a valid hex code, it will only let me type 5500. I have only tried this with 1.18.2 and Fabric so far, but it may be happening for other versions and modloaders.
![blurissue](https://github.com/Motschen/Blur/assets/138732006/61407ec8-2ca9-4ce7-a15f-fe0b08403559)

**Comment by Motschen** [comment]
The 1.18.2 version doesn't use hex colors, but integer colors instead.
This was changed in the 1.19 version, but I don't plan on backporting anything to outdated versions of Minecraft.
