### ISSUE TITLE
Incompatible with 1.20.2

### ISSUE THREAD

**Issue by RoonMoonlight** [Motschen/Blur#82]
Dunno if Minecraft had breaking change related to HUD, when I launched with Blur enabled on 1.20.2 the game crashes when initializing the game. Would be great if the mod could be updated to 1.20.2.

**Comment by TheMrEngMan** [comment]
Fixed by #81

**Comment by backryun** [comment]
https://github.com/Motschen/Blur/actions/runs/6376991359
use it, update complete.
