### ISSUE TITLE
Is the mod useless as of 1.20.5? Answer: No :)

### ISSUE THREAD

**Issue by KennyDevT** [Motschen/Blur#94]
The title.

**Comment by OfficialCRUGG** [comment]
Why would it be?

**Comment by KennyDevT** [comment]
Because minecraft natively added Blur into the game.

**Comment by OfficialCRUGG** [comment]
But Minecraft's Blur is where the dirt background used to be, not where it wasn't, which is what this mod is for.

**Comment by Motschen** [comment]
With Mojang's recent addition of a blur effect to vanilla Minecraft (snapshots), many people have declared the Blur mod dead. 💀 
However, quite the opposite is true – it's more alive than ever, as I've been working on a new update: Blur+ 🪩 
The mod's goal now is to improve upon the vanilla blur effect, adding smooth & configurable animations, the ability to apply it to containers (such as the inventory, chests, etc.), as well as customizable gradient backgrounds. 🌈 

I'll release a public beta soon, but here's already a little taste for yall:
https://nextcloud.midnightdust.eu/s/Rj5peojSGDEGKwy

The branch for Blur+ can be found here:
https://github.com/Motschen/Blur/tree/plus
